---
- name: Configure | /etc/fuse.conf | user_allow_other
  lineinfile:
    state: present
    dest: /etc/fuse.conf
    regexp: '^#?user_allow_other'
    line: user_allow_other
  tags:
    - configuration
    - fuse

- name: "Add {{ riofs_user }} to %fuse"
  user:
    name: "{{ riofs_user }}"
    groups: fuse
  when: riofs_user != 'root'

- name: Upload Config | RioFS
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: wcadmin
    mode: 0775
  with_items:
    - usr/local/etc/riofs/riofs.conf.xml
  tags:
    - configuration
    - template-configuration
