---
- name: Configure | /etc/fuse.conf | user_allow_other
  lineinfile:
    state: present
    dest: /etc/fuse.conf
    regexp: '^#?user_allow_other'
    line: user_allow_other
  tags:
    - configuration
    - fuse

- name: "Configure | {{ riofs_config_path }} | {{ item.regexp }}"
  replace:
    dest: "{{ riofs_config_path }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - regexp: '### AWS Access Key ID ###'
      replace: "{{ riofs_access_key_id }}"
    - regexp: '### AWS Secret Access Key ###'
      replace: "{{ riofs_secret_access_key }}"
